name: Release
on: 
  release: 
    types: [published]
permissions:
  contents: write

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install build-essential cmake python3 python3-dev python3-pybind11 pybind11-dev autoconf intltool libtool automake libgmp-dev libmpfr-dev libcurl4-openssl-dev libicu-dev libxml2-dev clang python3-pytest
      - name: Build
        run: |
          mkdir build && cd build
          cmake -DUSE_SYSTEM_LIBQALCULATE=OFF ..
          make -j $(nproc)
      - uses: softprops/action-gh-release@v2
        with:
          files: ./build/qalculate*.whl
      - run: pytest
